spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac
    username: root
    password: 123456
    # redis 配置
  data:
    redis:
      # 地址
      host: 127.0.0.1
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      password:
      # 连接超时时间
      timeout: 10s
      lettuc e:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
server:
  port: 8080
mybatis:
  type-aliases-package: cn.wolfcode.rbac.domain
  #bybatis配置信息
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


logging:
  level:
    root: info
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    com:
      wangweicheng:
        rbac:
          mapper: trace

#配置分页属性
pagehelper:
  reasonable: true
  page-size-zero: true
